services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isima
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080